# Generated by Django 3.2.5 on 2021-09-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.SmallIntegerField(default=0),
        ),
    ]
